import React from 'react';
import App from '../src/App.js';
import localStorageMock from '../src/localStorageMock'
import renderer from 'react-test-renderer';

beforeEach(() => {
    localStorageMock.setItem('msal.idtoken', 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkJCOENlRlZxeWFHckdOdWVoSklpTDRkZmp6dyJ9.eyJhdWQiOiJjMGZiNzliYS1iNzJjLTQ3YzEtOTEyYy00OGVlNmNiYWM5NzIiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vNjhiODY1ZDUtY2YxOC00YjJiLTgyYTQtYTRlZGRiOWM1MjM3L3YyLjAiLCJpYXQiOjE1NzMyMTg5NjUsIm5iZiI6MTU3MzIxODk2NSwiZXhwIjoxNTczMjIyODY1LCJhaW8iOiJBV1FBbS84TkFBQUFhZjNGZE13VksvOUVKaGdyYkc0M1J3YVhYMmF6cDB0dVU2V1k3SVdERUlHTmRkR0tCNlRlVWd4UUhabUZtN2dRNkF5N1VMNnhzSStFTHlqSnVPZmJsS0h4dktQdEhod1F6SFQvUzNQVWU4WnBuUG81Y2YxY0lwcUM2RGVERW1SOCIsIm5hbWUiOiJLZXJyeSwgU2hlaWxhIChBc3NvY2lhdGUgU29mdHdhcmUgRGV2ZWxvcGVyKSIsIm5vbmNlIjoiMTMyNDZkMTgtMGNlNy00MTZmLTllMzAtNGFkZGIyNGY0MTRhIiwib2lkIjoiYTEwMzQxYmUtMjRjYS00NWY5LWEyYWEtZjEyNzRjZjI2ZjhiIiwicHJlZmVycmVkX3VzZXJuYW1lIjoic2hlaWxhLmtlcnJ5QHNreS51ayIsInJvbGVzIjpbImFkbWluIl0sInN1YiI6IkJWeV9oN0wwZnBGamtXZ3dJaTVmd2NhYzZkYVM2QmZvNlJOZGF5a3hNYjAiLCJ0aWQiOiI2OGI4NjVkNS1jZjE4LTRiMmItODJhNC1hNGVkZGI5YzUyMzciLCJ1dGkiOiJ6aDdIcTRUNldraU85WWFqemI0LUFBIiwidmVyIjoiMi4wIn0.JWVqGskgxyBnn5NcGgNnPanDmpvd19LBXmz457gJvTnpsOgX-uXMrYPaGjMM6rKfQkAcgFkx6TmN26jnr3O3sG7KTgPs_4G6wXh3ZZf4px1LCwsBnKlHoznoIS26M88uZPGBZfHq7sFGH_80kCtqlwom7_0xsH0gpHi0TvRYLrilTyjVBQPX6ONg8U2art1d1Bu_DOt33I6d74hpvFpyG0Mj8Uw9HCzo0TT_OurShhZPU3QgDMDoBIUGYHsSOjkX7hk_jQKoOQbif2G3dOPOd02RiMtrSmYmoyJAVsK-jINF3kySNeYSvPlG3S-1nSAGrLAmk_MKHRNBsfxV5PIr6A')

});

test('Admin component only visible to admin', () => {
    const component = renderer.create(
        <App />
    )
    let tree = component.toJSON();
    expect(tree).toMatchSnapshot();
});