version: 2
jobs:
  build:
    working_directory: ~/agile-uni
  
    docker:
      - image: circleci/node:12.9.1
    steps:
      - add_ssh_keys:
            fingerprints:
              - "4f:49:fd:1e:d2:65:9c:dd:a9:72:68:da:f8:c8:7f:8e"
      - checkout
      - run: gpg agile_key.gpg
      - run: yarn install
      - run: yarn test
