version: 2
jobs:
  build:
    working_directory: ~/agile-uni
  
    docker:
      - image: circleci/node:12.9.1
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: agileuniversity
          MYSQL_DATABASE: agileuni
          MYSQL_PASSWORD: agileuniversity
      
    steps:
      - add_ssh_keys:
            fingerprints:
              - "4f:49:fd:1e:d2:65:9c:dd:a9:72:68:da:f8:c8:7f:8e"
      - checkout
      - run: sudo apt-get install -y git-crypt
      - run: gpg --no-tty --batch --passphrase "$gpgpassword" --pinentry-mode loopback --output agile_key  --decrypt agile_key.gpg
      - run: git-crypt unlock agile_key
      - run: yarn install
      - run: sudo apt-get update && sudo apt-get dist-upgrade
      - run: yarn add mysql
      - run:
          name: Install MySQL CLI; Import data
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u root -pagileuniversity agileuni < ddl_scripts/db_0.sql
            mysql -h 127.0.0.1 -u root -pagileuniversity agileuni < ddl_scripts/db_1.sql
            mysql -h 127.0.0.1 -u root -pagileuniversity agileuni < ddl_scripts/testdb_0.sql
      - run: yarn test
